DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO PRODUTO] IS NULL

ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO PRODUTO]
VARCHAR(20) NOT NULL

ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO PRODUTO])

